Remove compatibility code for EOL dependency versions
Remove NoSuchMethodError catch blocks and reflective fallbacks for
dependency versions that are no longer supported

See gh-50383

Signed-off-by: Sebastien Tardif <sebtardif@ncf.ca>